### ISSUE TITLE
Issues when attempting many requests in parallel

### ISSUE THREAD

**Issue by obsoleted** [PyriteServer/PyriteDemoClient#11]
There are a few issues that seem to show up when trying to load a lot of data in a short amount of time. Issues include:
- on the dynaimc lod scene failures to load groups of related cubes. This is usually the result of a coroutine failure when trying to acquire a resource that other routines need. 
- Unity/Game crashes

Fixes to consider:
- Having some configurable maximum for requests permitted at a time
- Retry logic for failures

**Comment by stefangordon** [comment]
Mitigated!
