### ISSUE TITLE
Enable/Disable manual response decompression on platforms as appropriate

### ISSUE THREAD

**Issue by obsoleted** [PyriteServer/PyriteDemoClient#13]
It seems that Windows standalone is not the only platform where manual decompression is needed. WebGL and android may need this also.

The extension methods in WWWExtensions should be updated as appropriate for each platform we care about.

**Comment by stefangordon** [comment]
Still work that needs to be done here?  Based on the Texture WWW stuff.

**Comment by obsoleted** [comment]
I guess we do not need this any more. Since we more or less backed off needing compression. Closing  now.
