### ISSUE TITLE
Add Octree class

### ISSUE THREAD

**Issue by obsoleted** [PyriteServer/PyriteDemoClient#3]
Copy the octree class into the client and work through any cross plat issues

**Comment by Foxman13** [comment]
You can assign this one to me if you want.

**Comment by obsoleted** [comment]
Sure :).

**Comment by obsoleted** [comment]
Also for this I think we discussed that it would be useful when, when copying the code from the server to the unity project, we leave out the XNA pieces and use Unity types instead.

**Comment by stephbu** [comment]
The Unity types are more or less drop-ins for the XNA classes, most issues are casing and order of cctor stuff.

**Comment by obsoleted** [comment]
This has been completed.
