### ISSUE TITLE
Cache downloaded Mesh/Texture to Local Storage

### ISSUE THREAD

**Issue by ritchielozada** [PyriteServer/PyriteDemoClient#5]

**Comment by obsoleted** [comment]
@ritchielozada I think this is done right? Unless you are using a different mechanism to get the data than PyriteLoader uses.

**Comment by ritchielozada** [comment]
The PyriteLoader setup is done.  I'm trying to setup a different cache to support full dump of the mesh as it is shown on the screen to support local/no-network setup.

**Comment by stefangordon** [comment]
It is a cloud streaming mesh renderer :) I don't think working with no network is super high-pri.

**Comment by ritchielozada** [comment]
yeah :) -- it's primarily for my debugging efforts and the ability to regenerate the mesh in unity coords.

**Comment by ritchielozada** [comment]
Using PyriteLoader implementation.
